### ISSUE TITLE
Question about input form valid values?

### ISSUE THREAD

**Issue by darrenfuller** [gjanders/SplunkVersionControl#12]
HI @gjanders, 

Trying to setup this app on a lab system with SHC and a HF (which is where the SpluVerCon will live)..    

A couple of questions: 

1) What values are valid in the includeEntities/excludeEntities input field?    Can you put a wildcard to pull all objects? 

2) What about includeOwner/excludeOwner?   Can you put a wildcard here? 

./Darren

**Comment by gjanders** [comment]
You can safely leave them both blank...
