### ISSUE TITLE
404 Not found when creating Splunk Version Control Backup data input

### ISSUE THREAD

**Issue by marcelloromani** [gjanders/SplunkVersionControl#13]
When I try to create the backup data input, I get a 404 not found error when submitting the input configuration form.

Splunk version: enterprise 8.0.1
SplunkVersionControl version: 1.0.9

How to reproduce:
* create a new splunk version control backup data input
* set `srcURL` to `http://my-splunk-instance:8000`
* set `srcUsername` and `srcPassword` to the login credentials
* set other fields
* click "Next"

expected: data input created
actual: a red message containing the splunk-generated "404 Not Found" HTML page.

**Comment by gjanders** [comment]
I suspect that you might have misunderstood the srcURL:
This the URL to be used for the REST API access of the Splunk instance, https://localhost:8089/ for example (does not have to be localhost)

Are you running your REST API on port 8089?

In that case it would be:
set srcURL to http://my-splunk-instance:8089
