### ISSUE TITLE
REST API not found

### ISSUE THREAD

**Issue by Thrawn-Smith** [gjanders/SplunkVersionControl#14]
Hello,

for Splunk version 8.0.4, SplunkVersionControl 1.1.0

I encounter an issue concerning restoration !
Items are correctly exported to Git server but impossible to restore them.

Here's the log of a failed object restoration attempt in **splunkversioncontrol_postversioncontrolrestore.log**

Any idea of the issue cause ?
How can I check that REST API for restoration is correctly installed ?
Thanks !

Thrawn

![image](https://user-images.githubusercontent.com/19730921/84946911-ab896c00-b0e9-11ea-9be4-f0c43baeccf0.png)

**Comment by gjanders** [comment]
I've released version 1.1.1 to try to fix that, can you try it please?

**Comment by VchampionV** [comment]
Thanks for releasing fix so quick !
It seems working now but I have to put correct object ID.

How can you grab URI of a deleted object in Splunk ?


![image](https://user-images.githubusercontent.com/19730921/84988855-0307f600-b143-11ea-8f50-01f137280505.png)

**Comment by gjanders** [comment]
If it's a search head cluster the conf.log might mention it.
In newer versions of splunk the audit.log may also record it...
