### ISSUE TITLE
Specify Git Repo Dir

### ISSUE THREAD

**Issue by edcaruso** [gjanders/SplunkVersionControl#15]
Today I setup your add-on and it worked amazing other then one thing. It completely wiped my repo. Now some of that was my fault as I did not realize I had to start with a clean repo. 

Our repo has a number of folders. One example (starting easy) is a HF folder where I want to back up everything from our Heavy Forwarder. 

Is there a way in your app I can specify the git folder location I want the app to use or does it need an entire repo per component? 

I did try and read your document’s but any info or feedback would be fantastic.

Thank you.

**Comment by gjanders** [comment]
It uses the entire repo by default, perhaps I can update the README.md to make that more clear?
Your git history should maintain your old repo information...apologies about the confusion

**Comment by edcaruso** [comment]
I think that’s okay! I thought the entire repo may be the only solution. I
was just hopeful I could use a specific folder. Thanks for your help and
fast response!

Have yourself a good night

**Comment by gjanders** [comment]
Updated the README.md on the master branch and the details tab on https://splunkbase.splunk.com/app/4355/#/details
