### ISSUE TITLE
Issues when creating the modular input in SplunkVersionControlBackup

### ISSUE THREAD

**Issue by andreeaf1301** [gjanders/SplunkVersionControl#17]
Hello,

After following the steps to configure the git backup, i noticed an error when i'm trying to save the modular input in SplunkVersionControlBackup:

 Splunkd daemon is not responding: ('Error connecting to /servicesNS/nobody/SplunkVersionControl/data/inputs/splunkversioncontrol_backup/splunk_backup: The read operation timed out',)

We use the app to backup a SplunkCloud instance from a remote Splunk instance. I have port 8089 opened.

My question is if the srcuser (used when create modular input) should have only api role or an admin role is needed as well and that's why I'm are getting the errors listed above?

Thank you,

Andreea

**Comment by gjanders** [comment]
Does the srcURL get printed in the message?
What have you set the srcURL to in the modular input?

**Comment by andreeaf1301** [comment]
srcUrl is not printed in the message.
Url is: https://cloudinstancehostaname:8089.

I tried to increase the splunkd connection timeout limit ( from 30 to 120) and now i'm getting this error: Encountered the following error while trying to save: Argument validation for scheme=splunkversioncontrol_backup: script running failed (killed by signal 9: Killed).


Thank you,

Andreea

**Comment by gjanders** [comment]
Can you try setting debugMode to true and then see if you get more hints in the splunkversion control backup logs?

**Comment by andreeaf1301** [comment]
I set debugMode=true
I'm seeing the following logs:

ModularInputs - Argument validation for scheme=splunkversioncontrol_backup: script running failed (killed by signal 9: Killed).
Argument validation for scheme=splunkversioncontrol_backup: killing process, because executing it took too long (over 30000 msecs)

 DEBUG    Running query against URL https://host.splunkcloud.com:8089/servicesNS/nobody/SplunkVersionControl/search/jobs/export?search=makeresults with username svc.splunk_backup proxies_length=0

**Comment by gjanders** [comment]
From the CLI of your splunk server running the modular input, can you run a curl or wget command to that endpoint?

**Comment by andreeaf1301** [comment]
wget https://.splunkcloud.com:8089
--2021-02-19 09:09:10--  https://.splunkcloud.com:8089/
Resolving splunkcloud.com (.splunkcloud.com)... X.X.X.X
Connecting to splunkcloud.com (.splunkcloud.com)|X.X.X.X|:8089... connected.

**Comment by gjanders** [comment]
Ok interesting. Any proxy at OS level?
I've put a proxy option into the app if required...

**Comment by andreeaf1301** [comment]
There is no proxt at OS level.
I noticed in the documentation when I want to configure a restore a splunk admin account is needed.
Do I need for backup an admin role  for the splunk user as well?

**Comment by gjanders** [comment]
For the first issue I would try...

splunk cmd python

Once open type or paste

import requests
res = requests.get("https://yourcloudurl:8089")
print(res.text)

If the above works it might be a misleading error.

A single admin user for backup and restore would ensure the app can backup any knowledge object in any app. But you could use a non admin user...you might hit a permissions issue at some point

**Comment by andreeaf1301** [comment]
Hi, 

Thank you for the troubleshooting steps provided above.
I think we have a transparent proxy on that server.
I tried using another server and worked.

Thank you for all the suggestions!

**Comment by gjanders** [comment]
No problem, glad you found the root cause here
