### ISSUE TITLE
OPENSSL_1.0.0 not found 

### ISSUE THREAD

**Issue by davidbono** [gjanders/SplunkVersionControl#3]
Hi,

Thanks for the great work you made.

When I configured the input, I had the message that OPENSSL 1.0.0 was not found.

To make it works, I had to add the following lines in python scripts 
``` os.unsetenv('LD_LIBRARY_PATH')``` 

David

**Comment by gjanders** [comment]
Thanks for opening this issue, it does sound like a potentially environment specific issue.
The python code is using the shell=True option, if your shell profile file (.bash_profile) or similar is modifying the LD_LIBRARY_PATH this would potentially be an issue.

Does SSH and git work on the shell of the Splunk server? If you login as the user running Splunk?

**Comment by davidbono** [comment]
Hello,
 
I am using Debian and installed Splunk with .deb package which create splunk user automatically.
I logged as splunk user and was able to generate ssh key, etc... I don't have particular shell profile. the one generate by default during installation I guess.

David

**Comment by gjanders** [comment]
Interesting, still a strange edge case.

Can you try the version here https://github.com/gjanders/SplunkVersionControl/tree/testing zip file is uploaded now

In this new version you will need to type true into that new field to have the os.unsetenv run...

**Comment by gjanders** [comment]
While I made that release it cannot pass appinspect as you cannot manipulate environment variables! Therefore I won't be able to put it live on SplunkBase, but feel free to test it and see if it helps...

**Comment by davidbono** [comment]
Give me some time to investigate into that Splunk default path user.
