### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by IanMoroney** [gjanders/SplunkVersionControl#8]
I couldn't find an obvious step by step guide on how to set this up. Do you have an example on how to get this backing up to github?

App is installed, as is git but that's as far as i got.
No idea if i should be creating a new github repo, generating a PAT token, or which directory to checkout the repo to etc.

**Comment by gjanders** [comment]
Create a new git repo, initialise the repo (it can have a README or can it be empty, but it must be at a point where the master branch exists)
The server doing the git backup *must* have SSH access to the repo without a username/password (in other words you need to have the SSH key setup so a git clone/git checkout/git push) all work without prompt for credentials
And then it should hopefully just work, perhaps I need to write this into the README

**Comment by IanMoroney** [comment]
Do you specify the folder location somewhere? like in an inputs.conf? is there documentation for that?
Thanks for the response so far!

**Comment by gjanders** [comment]
If you are on a search head cluster you want to specify the input via settings -> inputs on a standalone member, this is where you configure the various settings.
If your on a standalone search head you specify the input via settings -> inputs...

**Comment by gjanders** [comment]
Did you ever get this sorted? Thanks

**Comment by marcelloromani** [comment]
I had the same question and eventually figured I had to go on Settings -> Data Inputs -> Select "Splunk Version Control Backup" and then fill out the settings.

**Comment by edcaruso** [comment]
> Do you specify the folder location somewhere? like in an inputs.conf? is there documentation for that?
> Thanks for the response so far!

Hi gjanders/all! 

We store our backups inside a backups folder in our repo so I’d like to know as well how I can specify a specific folder for backup. Thanks in advance!!

**Comment by gjanders** [comment]
Normally I create a dedicated repo for a backup server/location as the code assumes it will use the top-level of the repository to create directories/store json files with the config in...
